const CORE_JAVA_QUESTIONS = [
  { topic: "JVM Basics", q: "What is the difference between the JVM, JRE, and JDK?", opts: ["The JVM compiles Java, the JRE debugs it, and the JDK deploys it", "The JVM runs bytecode, the JRE provides the runtime environment, and the JDK adds development tools", "The JDK runs bytecode, the JVM provides libraries, and the JRE adds compilers", "They are interchangeable terms"], ans: 1, exp: "The JVM executes bytecode. The JRE includes the JVM plus runtime libraries. The JDK includes the JRE plus tools like javac, javadoc, and jdb." },
  { topic: "OOP", q: "Which set best describes the core OOP ideas commonly discussed in Java interviews?", opts: ["Recursion, caching, sorting, parsing", "Encapsulation, inheritance, polymorphism, abstraction", "Compilation, interpretation, threading, networking", "Allocation, deallocation, serialization, reflection"], ans: 1, exp: "The standard OOP pillars are encapsulation, inheritance, polymorphism, and abstraction." },
  { topic: "OOP", q: "What is encapsulation in Java?", opts: ["Allowing one class to extend multiple classes", "Bundling data with methods and restricting direct access to internal state", "Turning methods into static utilities", "Storing all fields in interfaces"], ans: 1, exp: "Encapsulation hides implementation details and protects invariants, usually through private fields and a controlled public API." },
  { topic: "OOP", q: "What is the difference between abstraction and encapsulation?", opts: ["Abstraction hides unnecessary complexity; encapsulation protects internal state", "Abstraction and encapsulation mean the same thing", "Abstraction exposes fields; encapsulation hides methods", "Encapsulation is only for interfaces; abstraction is only for classes"], ans: 0, exp: "Abstraction is about showing only the essential view. Encapsulation is about controlling access to the internal representation." },
  { topic: "OOP", q: "What is polymorphism in Java?", opts: ["One interface or parent type can represent many concrete implementations", "A class can have multiple constructors only", "A subclass can have multiple parents", "All methods automatically become overridable"], ans: 0, exp: "Polymorphism lets code work through a parent type or interface while dispatching the correct implementation at runtime." },
  { topic: "Language", q: "What is the difference between overloading and overriding?", opts: ["Overloading changes behavior at runtime; overriding only at compile time", "Overloading uses the same method name with different parameters; overriding redefines a parent method in a subclass", "Overloading is only for constructors; overriding is only for interfaces", "They are two names for the same concept"], ans: 1, exp: "Overloading is compile-time resolution based on method signatures. Overriding is runtime dispatch of a subclass implementation." },
  { topic: "Collections", q: "What is the difference between ArrayList and LinkedList?", opts: ["ArrayList is backed by an array; LinkedList is node-based and usually better only for certain insertion/removal patterns", "LinkedList always gives faster random access", "ArrayList is thread-safe; LinkedList is not", "They have identical performance characteristics"], ans: 0, exp: "ArrayList is typically better for indexing and iteration. LinkedList is only preferable for specific structural modification patterns." },
  { topic: "Collections", q: "What is the main difference between HashMap and ConcurrentHashMap?", opts: ["HashMap sorts keys while ConcurrentHashMap does not", "HashMap is not thread-safe; ConcurrentHashMap supports safer concurrent access", "ConcurrentHashMap only stores integers", "HashMap is immutable, ConcurrentHashMap is mutable"], ans: 1, exp: "HashMap is not designed for concurrent mutation. ConcurrentHashMap allows concurrent reads and updates with much better behavior in multithreaded code." },
  { topic: "Collections", q: "What is the difference between HashSet and TreeSet?", opts: ["HashSet preserves insertion order; TreeSet preserves random order", "HashSet stores duplicates; TreeSet does not", "HashSet is usually faster and unordered; TreeSet keeps elements sorted", "TreeSet is always backed by a hash table"], ans: 2, exp: "HashSet is hash-based and usually offers faster average operations. TreeSet is tree-based and maintains sorted order." },
  { topic: "Equality", q: "What is the difference between == and equals() for objects in Java?", opts: ["== compares content and equals() compares references", "== compares references and equals() compares logical equality when overridden", "They always behave identically", "equals() only works for Strings"], ans: 1, exp: "For objects, == checks whether two references point to the same object. equals() is for logical equality if the class defines it properly." },
  { topic: "Equality", q: "Which statement correctly describes the equals() and hashCode() contract?", opts: ["If two objects have the same hashCode(), equals() must return true", "If equals() returns true, hashCode() must also be the same", "hashCode() is irrelevant to collections", "equals() must never be overridden without compareTo()"], ans: 1, exp: "Equal objects must have equal hash codes. The reverse is not required because collisions are allowed." },
  { topic: "Strings", q: "Why is String immutable in Java?", opts: ["So Strings can only be created once per JVM", "To support pooling, security, and safer sharing across code and threads", "Because the JVM cannot modify arrays", "To make garbage collection unnecessary for Strings"], ans: 1, exp: "Immutability enables String pooling, safer reuse, predictable hashing, and reduced risk in security-sensitive APIs." },
  { topic: "Strings", q: "What is the difference between StringBuilder and StringBuffer?", opts: ["StringBuilder is immutable; StringBuffer is mutable", "StringBuilder is unsynchronized and usually faster; StringBuffer is synchronized", "StringBuffer is newer and always preferred", "There is no difference after Java 8"], ans: 1, exp: "StringBuilder is usually preferred in single-threaded code. StringBuffer trades speed for synchronization." },
  { topic: "Generics", q: "What is the main purpose of generics in Java?", opts: ["To improve graphics performance", "To provide compile-time type safety and reduce casts", "To replace inheritance", "To make all collections thread-safe"], ans: 1, exp: "Generics let classes and methods work with typed parameters safely, which catches type mistakes at compile time." },
  { topic: "Generics", q: "What is type erasure?", opts: ["Removing unused classes during garbage collection", "The JVM deleting objects of generic types", "Generic type information being mostly removed at compile time so runtime uses raw types or bounds", "A process for clearing cache entries"], ans: 2, exp: "Java generics are mainly a compile-time feature. At runtime the JVM generally does not retain the full generic type information." },
  { topic: "Generics", q: "What does PECS stand for in Java generics?", opts: ["Parameter Equals Class Scope", "Producer Extends, Consumer Super", "Private Encapsulation Class Structure", "Pointer Execution Cache System"], ans: 1, exp: "PECS helps remember wildcard usage: use extends when you mainly read, and super when you mainly write." },
  { topic: "Exceptions", q: "What is the difference between checked and unchecked exceptions?", opts: ["Checked exceptions must be handled or declared; unchecked exceptions do not have that compile-time requirement", "Unchecked exceptions are always more serious", "Checked exceptions only happen in filesystems", "There is no real difference"], ans: 0, exp: "Checked exceptions are enforced by the compiler. Unchecked exceptions are RuntimeException subclasses and are not required in method signatures." },
  { topic: "Exceptions", q: "What is the difference between throw and throws?", opts: ["throw declares a method contract; throws actually raises an exception", "throw raises an exception instance; throws declares possible propagation in the method signature", "They are interchangeable", "throws is only for runtime exceptions"], ans: 1, exp: "throw appears in code to raise an exception. throws appears in the signature to declare checked exceptions that may escape." },
  { topic: "JVM Basics", q: "Which answer best describes common Java memory areas?", opts: ["Heap for objects, stack for method frames, metaspace for class metadata", "Only heap and cache exist in Java", "Everything is stored on the stack", "Only objects use memory in Java"], ans: 0, exp: "A standard interview answer mentions heap, per-thread stacks, and metaspace for class metadata." },
  { topic: "JVM Basics", q: "What is the difference between stack memory and heap memory?", opts: ["The stack stores objects globally; the heap stores local variables only", "The stack stores per-thread frames and locals; the heap stores shared objects", "They are the same thing with different names", "Heap memory is only for primitives"], ans: 1, exp: "The stack is per-thread and tied to method calls. The heap is shared and stores objects managed by garbage collection." },
  { topic: "Concurrency", q: "What does synchronized do in Java?", opts: ["It makes a variable immutable", "It ensures mutual exclusion around a block or method and provides visibility guarantees around locking", "It forces a method to run asynchronously", "It prevents a class from being extended"], ans: 1, exp: "synchronized uses a monitor lock so only one thread enters the protected section at a time, and it also helps coordinate memory visibility." },
  { topic: "Concurrency", q: "What does volatile guarantee?", opts: ["Atomicity for all operations", "Visibility of writes across threads, but not atomicity for compound operations", "That a thread will never be blocked", "That an object cannot be garbage collected"], ans: 1, exp: "volatile helps threads see the latest value, but expressions like count++ still are not atomic." },
  { topic: "Concurrency", q: "What is the difference between a process and a thread?", opts: ["A process is an independent program with its own resources; threads are lighter execution units within it", "Threads always have isolated heaps from each other", "Processes are created only inside the JVM", "There is no meaningful difference"], ans: 0, exp: "Processes own resources and memory spaces; threads share a process's memory but have separate call stacks." },
  { topic: "Concurrency", q: "What is a deadlock?", opts: ["A thread finishing too early", "Two or more threads waiting indefinitely on each other's locks", "A method running recursively", "The JVM pausing for garbage collection"], ans: 1, exp: "Deadlock is a circular wait over resources or locks. Common prevention techniques include consistent lock ordering and higher-level concurrency utilities." },
  { topic: "Concurrency", q: "What is the difference between Callable and Runnable?", opts: ["Callable returns a result and may throw checked exceptions; Runnable does not", "Runnable is only for daemon threads", "Callable cannot be submitted to executors", "Runnable always runs faster"], ans: 0, exp: "Callable is useful when work returns a value or throws checked exceptions, often alongside Future or ExecutorService." },
  { topic: "Language", q: "What is autoboxing?", opts: ["Automatic conversion between primitives and wrapper types", "Automatic conversion between classes and interfaces", "Automatic creation of arrays from lists", "Automatic synchronization of shared variables"], ans: 0, exp: "Autoboxing converts primitives like int to Integer, and unboxing converts the wrapper back to the primitive." },
  { topic: "Language", q: "Which list shows Java access modifiers from most open to most restricted?", opts: ["public, protected, package-private, private", "private, package-private, protected, public", "public, private, final, static", "protected, public, private, abstract"], ans: 0, exp: "A common interview ordering is public, protected, package-private, then private." },
  { topic: "Language", q: "Can constructors be inherited in Java?", opts: ["Yes, always", "Only if they are protected", "No, but a subclass can call a parent constructor with super(...)", "Only abstract constructors are inherited"], ans: 2, exp: "Constructors are not inherited. A subclass can invoke a parent constructor, but it does not inherit it as a member." },
  { topic: "OOP", q: "What is the difference between an interface and an abstract class?", opts: ["Interfaces are always faster", "Abstract classes can hold state and constructors; interfaces define a contract and can also have default/static methods", "Interfaces can extend classes", "Abstract classes support multiple inheritance of implementation"], ans: 1, exp: "A common interview answer is that abstract classes model shared base behavior and state, while interfaces model capabilities or contracts. Modern interfaces can have default methods, but they still do not replace abstract classes entirely." },
  { topic: "OOP", q: "What does the final keyword mean for a class, method, and variable?", opts: ["It always means immutable", "final class cannot be extended, final method cannot be overridden, final variable cannot be reassigned", "It only applies to methods", "It means a value is stored on the stack"], ans: 1, exp: "Interviewers often want to see whether you understand that final has different effects depending on where it is applied." },
  { topic: "Language", q: "What is the difference between final, finally, and finalize?", opts: ["They are related concurrency features", "final is a keyword, finally is a cleanup block, and finalize() was a GC-related hook that should not be relied on", "finally is used to create constants", "finalize() is how modern Java closes files"], ans: 1, exp: "This is a classic Java interview gotcha. finalize() is deprecated and should not be relied on for cleanup." },
  { topic: "Language", q: "Is Java pass-by-reference or pass-by-value?", opts: ["Pass-by-reference", "Pass-by-pointer", "Pass-by-value, including object references being passed by value", "It depends on the type"], ans: 2, exp: "Java is always pass-by-value. For objects, the value being copied is the reference, which is where the confusion usually comes from." },
  { topic: "Language", q: "What does static mean in Java?", opts: ["The member belongs to the class rather than to instances", "The member cannot be changed", "The member is thread-safe", "The member is stored in the stack"], ans: 0, exp: "Static members are associated with the class itself, which is why they can be accessed without creating an instance." },
  { topic: "Language", q: "What is a static block used for?", opts: ["To define an abstract method", "To initialize static state when the class is loaded", "To make a block synchronized", "To declare package-private fields"], ans: 1, exp: "Static initialization blocks run when the class is first loaded and are commonly used for more complex static setup." },
  { topic: "Language", q: "What is a functional interface?", opts: ["An interface with exactly one abstract method", "An interface used only for math", "An interface that cannot have default methods", "An interface that must extend Runnable"], ans: 0, exp: "Functional interfaces are the target types for lambdas and method references. They may still contain default and static methods." },
  { topic: "Language", q: "What is the purpose of default methods in interfaces?", opts: ["To allow interfaces to hold instance fields", "To add behavior to interfaces without breaking existing implementations", "To replace abstract classes in all cases", "To make methods final by default"], ans: 1, exp: "Default methods were introduced mainly to evolve interfaces more safely while keeping backward compatibility." },
  { topic: "Language", q: "What is the main benefit of enums over int constants?", opts: ["Enums are faster at runtime in every case", "Enums provide type safety and can have fields, methods, and behavior", "Enums can store duplicate values only", "Enums cannot be used in switch statements"], ans: 1, exp: "Enums are safer and richer than plain integer constants because they are real types with behavior." },
  { topic: "Collections", q: "What is the difference between List, Set, and Map?", opts: ["List stores key-value pairs, Set allows duplicates, Map preserves insertion order", "List is ordered and allows duplicates, Set stores unique values, Map stores key-value pairs", "They are interchangeable interfaces", "Set is a subtype of Map"], ans: 1, exp: "This is a foundational collections question. Interviewers often want a clean, fast explanation of the collection hierarchy." },
  { topic: "Collections", q: "Which map implementation maintains insertion order?", opts: ["HashMap", "TreeMap", "ConcurrentHashMap", "LinkedHashMap"], ans: 3, exp: "LinkedHashMap maintains insertion order while HashMap does not guarantee order and TreeMap sorts by key." },
  { topic: "Collections", q: "How does HashMap handle collisions conceptually?", opts: ["It rejects duplicate hash codes", "Multiple entries can land in the same bucket and are then distinguished using equals()", "It stores every key in a separate array", "It throws an exception when two keys collide"], ans: 1, exp: "A strong answer usually mentions buckets, hash codes, and then equals() being used to distinguish keys that land in the same bucket." },
  { topic: "Collections", q: "What is ConcurrentModificationException usually telling you?", opts: ["The JVM ran out of memory", "A collection was structurally modified while being iterated in a fail-fast context", "Two threads always accessed the same object", "A map key had a bad hashCode()"], ans: 1, exp: "This most often comes up when modifying a collection directly while iterating it with a fail-fast iterator." },
  { topic: "Collections", q: "What is the difference between Comparable and Comparator?", opts: ["Comparable defines natural ordering inside the class; Comparator defines external/custom ordering", "Comparator is built into Object and Comparable is not", "Comparable works only for numbers", "They are the same interface in different packages"], ans: 0, exp: "Comparable gives the type a natural ordering, while Comparator is useful when you need different sorting strategies outside the class." },
  { topic: "Collections", q: "When would you use a PriorityQueue in Java?", opts: ["When you need FIFO ordering only", "When you need fast access to the smallest or highest-priority element", "When you need thread safety by default", "When you need key-value storage"], ans: 1, exp: "PriorityQueue is heap-backed and is a common interview answer for top-k, scheduling, and repeated min/max extraction problems." },
  { topic: "Strings", q: "What is the String pool in Java?", opts: ["A thread pool used by String methods", "A cache of string literals and interned strings used to reduce duplicate String objects", "A collection implementation for text processing", "A special memory area outside the heap"], ans: 1, exp: "The String pool allows identical literals to be shared, which saves memory and is part of why String immutability matters." },
  { topic: "Strings", q: "Why is String preferred for keys, URLs, and security-sensitive values?", opts: ["Because String is mutable", "Because String is immutable, cacheable, and behaves predictably for equality and hashing", "Because String lives on the stack", "Because String is always faster than char[]"], ans: 1, exp: "Immutability makes String easier to reason about and safer to share. It also supports stable hashing and interning." },
  { topic: "Generics", q: "Can you create a new T() inside a generic class in Java?", opts: ["Yes, always", "Only when T extends Object", "No, not directly because of type erasure", "Only for primitive wrapper types"], ans: 2, exp: "Because of type erasure, Java does not retain enough runtime information to instantiate a generic type parameter directly." },
  { topic: "Generics", q: "Why can't you create arrays of generic types like new List<String>[10]?", opts: ["Because arrays are slower than lists", "Because generics use type erasure and arrays are reified, which leads to type-safety issues", "Because the JVM does not support arrays", "Because List is abstract"], ans: 1, exp: "This is a classic generics question. Arrays know their runtime component type, but generic type arguments are erased." },
  { topic: "Exceptions", q: "Will a finally block always execute?", opts: ["Yes, with no exceptions", "No, never", "Usually yes, except in cases like System.exit() or a JVM crash", "Only if the catch block runs"], ans: 2, exp: "The common interview answer is that finally runs in normal control flow, but there are edge cases where it may not." },
  { topic: "Exceptions", q: "What is try-with-resources used for?", opts: ["Retrying failed code", "Automatically closing resources that implement AutoCloseable", "Catching only checked exceptions", "Making code thread-safe"], ans: 1, exp: "try-with-resources reduces boilerplate and helps prevent resource leaks by closing resources automatically." },
  { topic: "Exceptions", q: "What is the difference between Exception and Error in Java?", opts: ["They are interchangeable", "Error represents serious JVM-level problems that applications usually should not try to handle like normal exceptions", "Error is for checked exceptions only", "Exception is only for I/O"], ans: 1, exp: "Interviewers often want to hear that Error is generally not something application code should recover from in the same way as exceptions." },
  { topic: "Concurrency", q: "What is the difference between wait() and sleep()?", opts: ["wait() pauses a thread without releasing locks, sleep() releases them", "wait() is called on an object and releases that monitor; sleep() pauses the current thread without releasing held monitors", "sleep() only works in synchronized blocks", "They are aliases"], ans: 1, exp: "This is a very common concurrency question. The monitor-release behavior is the key distinction." },
  { topic: "Concurrency", q: "What is the difference between notify() and notifyAll()?", opts: ["notify() wakes one waiting thread; notifyAll() wakes all waiting threads on that monitor", "notifyAll() only works for daemon threads", "notify() is deprecated and notifyAll() replaces it", "There is no difference"], ans: 0, exp: "The right choice depends on the coordination pattern, but interviewers usually want to hear that notifyAll() avoids some missed-signal style issues." },
  { topic: "Concurrency", q: "Why might you use AtomicInteger instead of volatile int?", opts: ["AtomicInteger is smaller in memory", "AtomicInteger supports atomic compound operations like incrementAndGet(), while volatile only gives visibility", "volatile cannot be read by other threads", "AtomicInteger makes code single-threaded"], ans: 1, exp: "This is another visibility-vs-atomicity question. Atomic classes help when you need thread-safe read-modify-write operations." },
  { topic: "Concurrency", q: "What is ExecutorService used for?", opts: ["Managing object serialization", "Managing threads and task execution without manually creating and coordinating raw threads", "Forcing all methods to run asynchronously", "Replacing synchronized blocks"], ans: 1, exp: "ExecutorService is the standard high-level API for running tasks using a thread pool or other managed execution strategy." },
  { topic: "Concurrency", q: "What is a daemon thread?", opts: ["A thread that always runs first", "A background thread that does not keep the JVM alive once only daemon threads remain", "A thread that cannot be interrupted", "A thread created by the garbage collector only"], ans: 1, exp: "Daemon threads are background helpers. The JVM can exit when only daemon threads remain." },
  { topic: "JVM Basics", q: "What is garbage collection in Java?", opts: ["Manual deletion of objects by developers", "Automatic reclamation of memory for objects that are no longer reachable", "Moving all objects to the stack", "A compile-time optimization only"], ans: 1, exp: "A simple, solid answer is that the JVM automatically reclaims memory from unreachable objects." },
  { topic: "JVM Basics", q: "When is an object eligible for garbage collection?", opts: ["When it has a finalize() method", "When it becomes unreachable from any live thread or GC root", "When it goes out of scope in any method", "Immediately after creation if not final"], ans: 1, exp: "Eligibility is based on reachability, not just scope or age." },
  { topic: "JVM Basics", q: "What usually causes StackOverflowError?", opts: ["Too many objects in the heap", "Deep or infinite recursion exhausting a thread stack", "A failed hashCode()", "Too many open files"], ans: 1, exp: "This is a common pair with heap questions: stack overflow is usually a recursion problem, not a heap allocation problem." },
  { topic: "JVM Basics", q: "What usually causes OutOfMemoryError?", opts: ["A thread was interrupted", "The JVM cannot allocate enough memory for an operation, often due to heap pressure or resource exhaustion", "A finally block failed", "A deadlock occurred"], ans: 1, exp: "Interviewers often expect you to distinguish heap/resource exhaustion from stack exhaustion." },
  { topic: "JVM Basics", q: "What is the role of a class loader in Java?", opts: ["It compiles Java source files", "It loads classes into the JVM at runtime", "It manages thread scheduling", "It replaces the garbage collector"], ans: 1, exp: "A high-level answer is enough for many interviews: class loaders are responsible for loading classes dynamically into the JVM." },
  { topic: "Streams", q: "What is the difference between intermediate and terminal Stream operations?", opts: ["Intermediate operations are lazy and build the pipeline; terminal operations trigger execution and produce a result or side effect", "Intermediate operations return primitives only", "Terminal operations always mutate the source collection", "There is no practical difference"], ans: 0, exp: "This is a very common Java 8+ question. The key word interviewers usually want to hear is lazy." },
  { topic: "Streams", q: "What is the difference between map() and flatMap()?", opts: ["map() transforms each element to one value, while flatMap() transforms to nested streams or collections and flattens them", "flatMap() sorts results automatically", "map() can only be used on lists", "They are identical"], ans: 0, exp: "flatMap() is commonly used when each input element can produce multiple output elements, such as splitting nested collections." },
  { topic: "Streams", q: "Why should you be careful with side effects in streams, especially parallel streams?", opts: ["Streams forbid method calls", "Side effects can make behavior harder to reason about and can introduce concurrency bugs in parallel execution", "The JVM ignores side effects in streams", "Streams cannot call instance methods"], ans: 1, exp: "A clean answer is that stream pipelines are easier to reason about when operations are stateless and side-effect free." },
  { topic: "Language", q: "What is Optional meant to help with?", opts: ["Replacing all nulls everywhere in Java", "Expressing that a result may or may not be present and making absence explicit in APIs", "Making methods synchronized", "Representing arrays of unknown size"], ans: 1, exp: "Interviewers usually want to hear that Optional can improve API clarity, not that it should be used for every field and parameter." },
  { topic: "Language", q: "What is a record in modern Java?", opts: ["A mutable data class with custom memory layout", "A concise way to declare immutable-ish data carriers with generated accessors and value-based methods", "A replacement for all classes", "A special collection type"], ans: 1, exp: "Records are useful for simple data carriers and commonly come up in modern Java conversations, especially for newer codebases." },

  // --- Modern Java ---
  { topic: "Modern Java", q: "What does var do in Java, and what does it NOT change about the type system?", opts: ["var makes Java dynamically typed like Python", "var infers the local variable type at compile time; the variable still has a fixed static type", "var is only valid inside lambda expressions", "var allows a variable to hold values of multiple types at runtime"], ans: 1, exp: "var (Java 10) uses local variable type inference. The type is resolved by the compiler at the point of declaration, so Java remains strongly typed. Avoid it when the right-hand side doesn't make the type obvious." },
  { topic: "Modern Java", q: "How do switch expressions (Java 14) differ from traditional switch statements?", opts: ["Switch expressions only work with Strings and enums", "Switch expressions return a value, support concise arrow syntax, and the compiler enforces exhaustiveness", "Switch expressions are only allowed in unit tests", "Switch expressions replace if-else chains but run slower"], ans: 1, exp: "Switch expressions use arrow syntax (case X -> ...), can return a value with yield, and require all cases to be handled when used as an expression. This eliminates fall-through bugs and makes the intent explicit." },
  { topic: "Modern Java", q: "What is the main benefit of text blocks (Java 15) for writing embedded content?", opts: ["They store strings permanently in the heap", "They allow multiline strings without escape sequences, preserving natural indentation", "They replace StringBuilder for all concatenation", "They embed binary data in source files"], ans: 1, exp: "Text blocks use triple-double-quote delimiters (\"\"\") and automatically strip common leading whitespace, making embedded JSON, SQL, or HTML dramatically more readable without manual escaping." },
  { topic: "Modern Java", q: "What members does a record automatically generate from its component list?", opts: ["Only a toString() method", "A canonical constructor, component accessor methods (no get prefix), equals(), hashCode(), and toString()", "Getter methods with the get prefix and a no-arg constructor", "Only equals() and hashCode()"], ans: 1, exp: "Records (Java 16) generate a canonical constructor, accessors named after the components (e.g., name() not getName()), and correct implementations of equals(), hashCode(), and toString() based on all components." },
  { topic: "Modern Java", q: "Which statement about what a record can and cannot do is correct?", opts: ["Records can extend any class and implement any interface", "Records implicitly extend java.lang.Record, cannot extend other classes, but can implement interfaces and have instance methods", "Records cannot have any methods beyond the auto-generated ones", "Records are mutable unless you annotate them with @Immutable"], ans: 1, exp: "Because records implicitly extend java.lang.Record they cannot extend another class, but they can implement interfaces, define static members, instance methods, and compact constructors for validation." },
  { topic: "Modern Java", q: "What does pattern matching for instanceof (Java 16) eliminate?", opts: ["The need for null checks before casting", "The explicit cast that previously had to follow an instanceof check", "The need for generics in collections", "The use of equals() for type comparison"], ans: 1, exp: "Pattern matching lets you write if (obj instanceof String s) and use s directly in scope, eliminating the redundant cast String s = (String) obj that used to follow the check." },
  { topic: "Modern Java", q: "What problem do sealed classes (Java 17) solve that regular classes and interfaces cannot?", opts: ["They prevent all instantiation of a class hierarchy", "They restrict which classes may extend or implement them, making type hierarchies closed and enabling exhaustive pattern matching", "They make all fields final automatically", "They replace interfaces for all API design"], ans: 1, exp: "Sealed classes use the sealed keyword and a permits clause to define exactly which types can extend them. This allows the compiler to verify that pattern matching handles every possible subtype, which is valuable for modeling closed domain hierarchies." },
  { topic: "Modern Java", q: "What problem do virtual threads (Java 21) primarily address compared to platform threads?", opts: ["They replace synchronized for all concurrent access", "They allow running Java on multiple machines simultaneously for the first time", "They enable high-throughput concurrency for I/O-bound tasks without the memory cost of one OS thread per task", "They make garbage collection run in a background thread automatically"], ans: 2, exp: "Virtual threads are JVM-managed lightweight threads. They solve the scalability ceiling of the one-OS-thread-per-request model: blocking a virtual thread does not block the underlying carrier thread, so you can have millions of concurrent tasks without the large per-thread memory overhead." },
  { topic: "Modern Java", q: "How are virtual threads fundamentally different from platform threads?", opts: ["Virtual threads share memory across JVM instances", "Virtual threads are managed by the JVM scheduler, are cheap to create, and release the carrier thread when they block on I/O", "Virtual threads are always faster for CPU-intensive computation", "Virtual threads automatically synchronize access to shared state"], ans: 1, exp: "Platform threads map 1:1 to OS threads and are expensive to create and block. Virtual threads are multiplexed by the JVM onto a small carrier thread pool. When a virtual thread blocks (e.g., on I/O), the JVM parks it and frees the carrier thread for other work, making them ideal for I/O-bound workloads." },

  // --- Concurrency (continued) ---
  { topic: "Concurrency", q: "What is CompletableFuture used for in Java?", opts: ["Managing database connection pools", "Composing async operations with callbacks, combining futures, and handling errors in a non-blocking pipeline", "Replacing the synchronized keyword for all concurrency", "Scheduling tasks that repeat on a fixed interval"], ans: 1, exp: "CompletableFuture (Java 8+) enables non-blocking async programming with a fluent API. Key methods include thenApply, thenCompose, thenCombine, and exceptionally. It is commonly asked in senior interviews about async design and thread coordination." }
];

const ALGORITHM_QUESTIONS = [
  { topic: "Complexity", q: "What does time complexity describe?", opts: ["How much memory code uses", "How runtime grows as input size grows", "How many variables a function has", "How fast the CPU clock is"], ans: 1, exp: "Time complexity describes how runtime scales with input size, usually using Big O notation." },
  { topic: "Complexity", q: "Which Big O complexity is usually better for large input sizes?", opts: ["O(n²)", "O(n log n)", "O(2ⁿ)", "O(n!)"], ans: 1, exp: "O(n log n) grows much more slowly than quadratic or exponential complexities as input increases." },
  { topic: "Arrays & Strings", q: "When is a two-pointer approach most likely useful?", opts: ["When you need recursion only", "When working with sequential data where moving left/right boundaries helps", "When storing key-value pairs", "When traversing a graph level by level"], ans: 1, exp: "Two pointers are great for sorted arrays, partitions, reversals, and scanning from both ends or with moving boundaries." },
  { topic: "Arrays & Strings", q: "What is the main idea of sliding window?", opts: ["Repeatedly sorting subarrays", "Maintaining a dynamic contiguous range while expanding or shrinking it", "Always using two nested loops", "Traversing a binary tree recursively"], ans: 1, exp: "Sliding window is commonly used for substring/subarray problems involving contiguous ranges." },
  { topic: "Arrays & Strings", q: "If an array is sorted and you need to find a target quickly, which approach often helps first?", opts: ["Depth-first search", "Binary search", "Union-find", "Topological sort"], ans: 1, exp: "Binary search is a natural first option on sorted arrays because it reduces the search space by half each step." },
  { topic: "Hashing", q: "What kind of problem is a hash map especially good for?", opts: ["Maintaining sorted order by default", "Fast lookups for frequencies, complements, and seen-before checks", "Traversing trees in order", "Finding shortest paths with weights"], ans: 1, exp: "Hash maps shine when you need near-constant-time membership checks or frequency counts." },
  { topic: "Hashing", q: "What is the classic tradeoff when using a hash map to speed up a solution?", opts: ["More memory for less time", "Less memory for more time", "Less correctness for more speed", "More recursion for less iteration"], ans: 0, exp: "Many interview problems become faster by using extra space for a lookup structure." },
  { topic: "Sorting", q: "Why do candidates often sort first before solving an interview problem?", opts: ["Sorting always gives O(1) solutions", "Sorting can expose structure that simplifies duplicates, intervals, or two-pointer logic", "Sorting makes hash maps unnecessary in every case", "Sorting is required before using loops"], ans: 1, exp: "Sorting can make relationships easier to reason about, even though it adds an O(n log n) preprocessing step." },
  { topic: "Stacks & Queues", q: "Which structure is most natural for matching parentheses problems?", opts: ["Queue", "Stack", "Heap", "Trie"], ans: 1, exp: "Stacks fit nested structure problems because the most recent opening bracket must be matched first." },
  { topic: "Stacks & Queues", q: "Which structure is most natural for breadth-first search?", opts: ["Stack", "Queue", "Hash set", "Linked list"], ans: 1, exp: "BFS explores level by level, so a queue is the standard worklist structure." },
  { topic: "Linked Lists", q: "What is the classic fast/slow pointer technique often used for?", opts: ["Tree balancing", "Cycle detection or finding a middle node", "Hash collision resolution", "Topological ordering"], ans: 1, exp: "Fast and slow pointers are commonly used in linked list problems for cycle detection and midpoint discovery." },
  { topic: "Linked Lists", q: "Why is reversing a linked list a common interview problem?", opts: ["It tests pointer manipulation and careful state updates", "It requires dynamic programming", "It can only be solved recursively", "It mainly tests sorting knowledge"], ans: 0, exp: "Reversing a linked list is simple in concept but exposes whether someone can manage references safely." },
  { topic: "Trees", q: "What is the main difference between DFS and BFS on a tree?", opts: ["DFS uses a stack/recursion depth-first, BFS uses a queue level-by-level", "BFS can only be recursive", "DFS always uses less memory", "They visit nodes in the same order"], ans: 0, exp: "DFS and BFS differ in traversal order and often in memory profile depending on the tree shape." },
  { topic: "Trees", q: "In a binary search tree, what property is usually true?", opts: ["All left descendants are smaller and all right descendants are larger", "Every node has exactly two children", "The tree is always balanced", "The root is always the median"], ans: 0, exp: "The BST ordering property enables faster search, insertion, and deletion in well-shaped trees." },
  { topic: "Trees", q: "What traversal of a BST gives sorted output?", opts: ["Preorder", "Postorder", "Inorder", "Level order"], ans: 2, exp: "An inorder traversal visits BST nodes in sorted order." },
  { topic: "Graphs", q: "When do you usually reach for BFS on a graph?", opts: ["When looking for the shortest path in an unweighted graph", "When you need to sort an array", "When you need constant-time lookups", "When you need to reverse a linked list"], ans: 0, exp: "BFS is a strong default for shortest path in unweighted graphs because it explores by distance layers." },
  { topic: "Graphs", q: "What is the difference between DFS and BFS in graph traversal interviews?", opts: ["DFS explores along a path before backtracking; BFS explores layer by layer", "DFS requires weights and BFS does not", "BFS cannot handle cycles", "They always use the same memory"], ans: 0, exp: "A clean explanation of traversal order and data structures is usually what interviewers want here." },
  { topic: "Graphs", q: "Why do graph traversals often need a visited set?", opts: ["To sort nodes by value", "To avoid infinite loops or repeated work in cyclic graphs", "To reduce all runtimes to O(1)", "To store edge weights only"], ans: 1, exp: "Visited tracking prevents revisiting nodes and is essential in graphs that may contain cycles." },
  { topic: "Heaps", q: "When is a heap or priority queue especially useful?", opts: ["When you need repeated access to the current min or max", "When you need random access by index", "When you need to preserve insertion order", "When you need fast string concatenation"], ans: 0, exp: "Heaps are ideal for top-k, streaming min/max, and scheduling style problems." },
  { topic: "Intervals", q: "What is a common first step for merging overlapping intervals?", opts: ["Reverse the list", "Sort intervals by start time", "Put all intervals in a hash map", "Traverse with BFS"], ans: 1, exp: "Sorting by start time makes it easy to scan once and merge overlapping intervals." },
  { topic: "Binary Search", q: "What kind of problem besides direct lookup often uses binary search?", opts: ["Finding the first valid answer in a monotonic search space", "Checking graph cycles only", "Calculating hash codes", "Building linked lists"], ans: 0, exp: "Binary search is often used on answers when a predicate changes from false to true across an ordered search space." },
  { topic: "Dynamic Programming", q: "What usually signals that dynamic programming might help?", opts: ["Repeated overlapping subproblems and optimal substructure", "Any problem involving arrays", "Any problem involving sorting", "Any problem with recursion is automatically DP"], ans: 0, exp: "DP becomes useful when brute force repeats the same subproblems and you can cache or build from smaller results." },
  { topic: "Dynamic Programming", q: "What is memoization?", opts: ["Sorting smaller subarrays first", "Storing results of solved subproblems so recursion does not recompute them", "Using a queue inside recursion", "Splitting a graph into layers"], ans: 1, exp: "Memoization is top-down dynamic programming with caching." },
  { topic: "Backtracking", q: "When is backtracking a common fit?", opts: ["When exploring combinations, permutations, or constrained search spaces", "When finding the median of two numbers", "When using only hash maps", "When the input is already sorted"], ans: 0, exp: "Backtracking explores choices incrementally and undoes them when a path stops being valid." },
  { topic: "Greedy", q: "What is the key idea behind a greedy algorithm?", opts: ["Always use recursion", "Make the locally best-looking choice and hope it leads to a global optimum", "Try every possibility exhaustively", "Store every intermediate result in a table"], ans: 1, exp: "Greedy algorithms work only when the problem has the right structure, so correctness needs justification." },
  { topic: "Recursion", q: "What are the two things you usually want to verify in a recursive solution?", opts: ["Base case and recursive progress toward it", "Queue order and heap balance", "Hash collisions and sorting stability", "Graph weights and visited count"], ans: 0, exp: "Interviewers usually want to hear that recursion needs a correct base case and guaranteed progress toward termination." },
  { topic: "Problem Solving", q: "What is usually the best interview move after finding a brute-force solution?", opts: ["Stop immediately", "Explain the complexity and then look for a better data structure or pattern", "Rewrite the same code with shorter variable names", "Jump to implementation without discussion"], ans: 1, exp: "Strong candidates communicate tradeoffs, name the bottleneck, and then optimize intentionally." },
  { topic: "Problem Solving", q: "Why do interviewers care so much about space complexity too?", opts: ["Because time complexity never matters", "Because some optimizations trade memory for speed, and memory constraints can change the right design", "Because arrays use no memory", "Because recursion is always free"], ans: 1, exp: "A balanced answer includes both time and space, especially when using hash maps, recursion, or DP tables." }
];

const ALGORITHM_GUIDES = [
  {
    icon: "🧠",
    title: "Core patterns",
    description: "The repeat offenders in coding rounds.",
    bullets: ["Hash maps and frequency counting", "Two pointers and sliding window", "Stacks, queues, and linked lists", "Binary search on data or answers"]
  },
  {
    icon: "🌳",
    title: "Traversal patterns",
    description: "The data-structure questions that show up constantly.",
    bullets: ["Tree DFS and BFS", "Graph traversal with visited sets", "Shortest path in unweighted graphs", "BST ordering and inorder traversal"]
  },
  {
    icon: "📈",
    title: "Optimization lens",
    description: "What to say after your brute-force idea is correct.",
    bullets: ["Name the bottleneck", "Trade memory for speed when useful", "Use sorting to expose structure", "Cache overlapping subproblems"]
  }
];

const SYSTEM_DESIGN_TRACKS = [
  {
    icon: "🏗️",
    title: "Interview structure",
    description: "A reliable way to start strong instead of jumping straight into boxes and arrows.",
    bullets: ["Clarify scope and traffic", "Define APIs and data model", "Estimate scale early", "Name the main bottlenecks"]
  },
  {
    icon: "🗃️",
    title: "Storage tradeoffs",
    description: "Be ready to explain why you would choose one persistence model over another.",
    bullets: ["SQL vs NoSQL", "Read-heavy vs write-heavy", "Indexing and partitioning", "Caching strategy"]
  },
  {
    icon: "🌐",
    title: "Scalability topics",
    description: "These are the knobs interviewers expect you to bring up naturally.",
    bullets: ["Load balancers", "Horizontal scaling", "Queues and async workers", "Replication and failover"]
  },
  {
    icon: "🛡️",
    title: "Operational thinking",
    description: "Strong answers go beyond architecture and cover how the system behaves in production.",
    bullets: ["Monitoring and alerting", "Backpressure and retries", "Rate limiting", "Consistency vs availability"]
  }
];
